services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only build development stage from dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
    - .env
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - ${NESTJS_LOCAL_PORT}:3000
    depends_on:
      - redis
      - mysql

  redis: # Redis container
    image: redis
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data

  mysql: # MySQL container
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_LOCAL_PORT}:${DB_PORT}
    volumes:
      - mysql:/var/lib/mysql
  

# Volumes to persist redis data
volumes:
  redis:
    driver : local
  mysql:
    driver : local